// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using Triplann.Data;

namespace Triplann.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180308213221_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Triplann.Models.ApplicationUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.HasKey("UserId");

                    b.ToTable("ApplicationUser");
                });

            modelBuilder.Entity("Triplann.Models.ChecklistItem", b =>
                {
                    b.Property<int>("ChecklistItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChecklistAction")
                        .IsRequired();

                    b.Property<int>("TripTypeId");

                    b.HasKey("ChecklistItemId");

                    b.HasIndex("TripTypeId");

                    b.ToTable("ChecklistItem");
                });

            modelBuilder.Entity("Triplann.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ApplicationUserId");

                    b.Property<string>("Duration")
                        .IsRequired();

                    b.Property<string>("Location")
                        .IsRequired();

                    b.Property<int>("TripTypeId");

                    b.HasKey("TripId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("TripTypeId");

                    b.ToTable("Trip");
                });

            modelBuilder.Entity("Triplann.Models.TripType", b =>
                {
                    b.Property<int>("TripTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActivityType");

                    b.Property<string>("TravelMethod");

                    b.Property<string>("UserId");

                    b.Property<string>("WeatherType");

                    b.HasKey("TripTypeId");

                    b.ToTable("TripType");
                });

            modelBuilder.Entity("Triplann.Models.ChecklistItem", b =>
                {
                    b.HasOne("Triplann.Models.TripType", "TripType")
                        .WithMany()
                        .HasForeignKey("TripTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Triplann.Models.Trip", b =>
                {
                    b.HasOne("Triplann.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Triplann.Models.TripType", "TripType")
                        .WithMany()
                        .HasForeignKey("TripTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
